### ISSUE TITLE
issues when make install

### ISSUE THREAD

**Issue by jlspzw** [gerbenvoshol/PRCx#1]
Hi Dear Author,

I try ro install the program in our cluster by the following command

./configure --prefix=mypath
###### new Makefile and configure.status generated by last step

then

make

I got the following error messages. 

______________________________________________________________________________________________________
gcc -O3 -Wall -D __unix -DPROF_HMM_TRANS=PLAN9 -DPAIR_HMM_STATES=SPACE5 -DPAIR_HMM_TRANS=ALL_TRANS -c HMM.c
HMM.c: In function 'read_HMM_SAM3x_binary':
HMM.c:1024:20: warning: 'iindex' may be used uninitialized in this function [-Wmaybe-uninitialized]
  int     i, dummy, iindex, findex, m = 0;
                    ^
HMM.c:1024:28: warning: 'findex' may be used uninitialized in this function [-Wmaybe-uninitialized]
  int     i, dummy, iindex, findex, m = 0;
                            ^
gcc -O3 -Wall -D __unix -DPROF_HMM_TRANS=PLAN9 -DPAIR_HMM_STATES=SPACE5 -DPAIR_HMM_TRANS=ALL_TRANS -c context.c 
context.c: In function 'prc_sum':
context.c:241:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 1; i < n; i++) {
  ^
context.c:241:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
context.c: In function 'calc_posterior_probabilities_profile':
context.c:520:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < cs4000->size; i++) {
  ^
context.c:528:3: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
   for(int n = begin, k = begin - index + cs4000->center; n < end; ++n, ++k) {
   ^
context.c:530:4: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
    for (int a = 0; a < cs4000->nalph; ++a) {
    ^
context.c:547:11: error: redefinition of 'i'
  for (int i = 0; i < cs4000->size; i++) {
           ^
context.c:520:11: note: previous definition of 'i' was here
  for (int i = 0; i < cs4000->size; i++) {
           ^
context.c:547:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < cs4000->size; i++) {
  ^
context.c:552:11: error: redefinition of 'i'
  for (int i = 0; i < cs4000->size; i++) {
           ^
context.c:547:11: note: previous definition of 'i' was here
  for (int i = 0; i < cs4000->size; i++) {
           ^
context.c:552:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < cs4000->size; i++) {
  ^
context.c: In function 'calc_posterior_probabilities_sequence':
context.c:575:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < cs4000->size; i++) {
  ^
context.c:582:3: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
   for(int n = begin, k = begin - index + cs4000->center; n < end; ++n, ++k) {
   ^
context.c:597:11: error: redefinition of 'i'
  for (int i = 0; i < cs4000->size; i++) {
           ^
context.c:575:11: note: previous definition of 'i' was here
  for (int i = 0; i < cs4000->size; i++) {
           ^
context.c:597:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < cs4000->size; i++) {
  ^
context.c:602:11: error: redefinition of 'i'
  for (int i = 0; i < cs4000->size; i++) {
           ^
context.c:597:11: note: previous definition of 'i' was here
  for (int i = 0; i < cs4000->size; i++) {
           ^
context.c:602:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < cs4000->size; i++) {
  ^
context.c: In function 'init_cs_weights':
context.c:621:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 1; i <= cs->center; i++) {
  ^
context.c: In function 'profile_to_discrete_alphabet':
context.c:735:3: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
   for (int n = 0; n < cs219->size; n++) {
   ^
context.c: In function 'assign_match_columns_by_gap_rule':
context.c:1188:9: warning: variable 'neff' set but not used [-Wunused-but-set-variable]
  double neff;
         ^
make: *** [context.o] Error 1

________________________________________________________________________________________________

Is there any special library I need install before make it or the source code has bugs?

Thank you.
Best

**Comment by gerbenvoshol** [comment]
Dear jlspzw,

I updated the code and removed the C99/C11 "int i", "int n" and "int k" declarations. Out of curiosity, what version of GCC are you using?

Could you try compiling with the new version?

hope it helps.

regards,

Gerben
