### ISSUE TITLE
Can't run tree because of a non-existent empty line

### ISSUE THREAD

**Issue by lukaszsobala** [gerbenvoshol/PRCx#3]
Hello,

I wanted to run prcX, so I downloaded the release version (2019.1) compiled it, created a library file and tried to run it (with the -tree option). However, every time it complains about this:

`Scoring     : .Please remove the empty line from ./library.lib at line 165!`

There is no empty line there.
I there might be something wrong with line 688 of file prc.c, but I am not a programmer so I'm not sure.

EDIT: I just tried the git version and it suffers from the same problem.

EDIT2: I changed line 687 from:
`		for (n = i + 1; n < n_models; n++) {`
to:
`		for (n = i + 1; n < n_models - 1; n++) {`
not sure what I did but now it works. Could you explain why it did not work?

EDIT3:
It worked, but it seems that it went through all the models and then stopped.
`Scoring     : .......................................................................................................................................Please remove the empty line from ./library.lib at line 165!`

EDIT4: OK I isolated the problem. `n_models` is, for some reason, always 1 larger than the number of models (unless it is by design...)

**Comment by lukaszsobala** [comment]
I can't figure this out. No matter what I do, either the empty line error message triggers from the outside loop (line 672) or from the inside loop (line 687) triggers. I think there is a problem with the program thinking there is one more line in the library file than there actually is, and no matter what I do it always thinks this. 

Please help.

**Comment by gerbenvoshol** [comment]
Hi, the library file is indeed a bit iffy. The last line in the file should not be terminated with an enter (\n). If you want, you can send it to me and I can have a look.

There is also an example lib file in the examples folder used for the publication that you can have a look at.

**Comment by lukaszsobala** [comment]
OK, you are right. The is no "LF" at the end of the line of your library file and that's why it works. But I can't get any programs not to insert this at the end.

Finally I found this way:
`perl -pi -e 'chomp if eof' library.lib`

This removes the last line ending from the file.

**Comment by gerbenvoshol** [comment]
Happy you managed to find a solution to your issue!
